// Code generated by "stringer -type deviceState -trimprefix=deviceState"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[deviceStateNew-0]
	_ = x[deviceStateDown-1]
	_ = x[deviceStateUp-2]
	_ = x[deviceStateClosed-3]
}

const _deviceState_name = "NewDownUpClosed"

var _deviceState_index = [...]uint8{0, 3, 7, 9, 15}

func (i deviceState) String() string {
	if i >= deviceState(len(_deviceState_index)-1) {
		return "deviceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _deviceState_name[_deviceState_index[i]:_deviceState_index[i+1]]
}
